# API: conexión pooled
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Flyway: conexión directa
spring.flyway.url=${FLYWAY_DATABASE_URL}
spring.flyway.user=${FLYWAY_DATABASE_USERNAME:${SPRING_DATASOURCE_USERNAME}}
spring.flyway.password=${FLYWAY_DATABASE_PASSWORD:${SPRING_DATASOURCE_PASSWORD}}

spring.jpa.show-sql=false

logging.level.root=INFO
logging.level.com.bluedigi.bluememo=INFO

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

server.forward-headers-strategy=framework